### ISSUE TITLE
VRDP listening on localhost only not on all?

### ISSUE THREAD

**Issue by ghost** [jazzdd86/phpVirtualbox#11]
# Issue
If I create a VM using vboxmanage from the command line with vrdp enabled I can see the port (9000) listening on all interfaces. However, if I create a VM through phpvirtualbox I can see the port (9000) listening on just 127.0.0.1. Because I am running a headless VirtualBox server I therefore cannot RDP on to the VM to install etc.

# Config
The relevant config info is:

docker-compose.yml environments for the container:

    environment:
      SRV_HOSTPORT: ${SRV}
      SRV_NAME: ${SRV_LABEL}
      SRV_USER: ${USR}
      SRV_PW: ${PASSWD}
      CONF_browserRestrictFolders: "/home,/usr/lib/virtualbox,/storage1,/storage2"
      CONF_consoleHost: "10.0.0.130"

GUI display on a newly created VM through phpvirtualbox shows:

    Remote Desktop Server Port:  9000  (10.0.0.130:9000)

# Platform
I am running VirtualBox 6 on CentOS 7.5 natively along with your container using Docker 18.09 (Compose 1.22.0)

**Comment by ghost** [comment]
# Update 1

I've noticed that there is an extra line in the .vbox file when a VM is created through the container rather than the command line, I.E.:
`<Property name="TCP/Address" value="127.0.0.1"/>`

As soon as I can I will set up a non-container install of phpvirtualbox and see if I get the same problem, to confirm whether it is phpvirtualbox itself that has the issue.

**Comment by jazzdd86** [comment]
Hi thanks for poinitng me to that issue.

I found a similar issue at https://github.com/phpvirtualbox/phpvirtualbox/issues/144 and found my config.php was not up to date.

So I added the $vrdeaddress option and pointed it to 0.0.0.0. Normally it is only bound to localhost for security reasons.

I tested it on my setup and now it works as expected.
