### ISSUE TITLE
VirtualBox 6.1

### ISSUE THREAD

**Issue by csdevto** [jazzdd86/phpVirtualbox#16]
Hi, is there anyway to make it compatible with virutalbox 6.1?

**Comment by MenosGrandes** [comment]
Hi,
You can just change Dockerfile a little bit:
` && wget --no-check-certificate https://github.com/phpvirtualbox/phpvirtualbox/archive/5.2-1.zip -O phpvirtualbox.zip \`
into 
`  && wget --no-check-certificate https://github.com/phpvirtualbox/phpvirtualbox/archive/develop.zip -O phpvirtualbox.zip \`

It works for me.

**Comment by jazzdd86** [comment]
chpatton013 made a merge request which added a  build-arg to control the release version, therefore you won't need to change the dockerfile anymore but can use PHP_VIRTUAL_BOX_RELEASE build-arg. Hope this helps
