### ISSUE TITLE
Enable authentication

### ISSUE THREAD

**Issue by stieler-it** [jazzdd86/phpVirtualbox#7]
I want to deploy an internet facing phpVirtualBox. Is it possible to re-enable the authentication?

In the config file I saw
```
    // Disable authentication
    var $noAuth = true;
```

I tried to set `-e CONF_noAuth=false` which leads to an override of

```
array (
  'noAuth' => 'false',
)
```

I assume the string 'false' will also be truthy for phpVirtualBox and authentication is still disabled.

Any way of achieving this?

**Comment by jazzdd86** [comment]
As far as I know, the default is to use authentication. So you have to disable the noAuth line with the comment sign. I searched the docs of phpvirtualbox and that seemed the only valid possibility as my default config file uses the noAuth=true line.

By now there is no possibility to do this via environment options. You need to edit the config.php manually. I will look into it and update the image as soon as I have time (which could be a few months).

**Comment by stieler-it** [comment]
Ok, just wanted to make sure there is no "official" way of achieving it. I will probably stick with the manual fix, if not I'll comment on how it can be solved. Thanks

**Comment by JuliusSenkus** [comment]
Hi, it seems issue still persist, are there any plans for this?

**Comment by jazzdd86** [comment]
Hi, its still not working, I am planning to update the docker image during January. I will post any update concerning this issue.

**Comment by jazzdd86** [comment]
Authentication is now enabled by default.
You have to use CONF_noAuth='true' environment variable to disable authentication.
