### ISSUE TITLE
Build fails on Alpine 3.8

### ISSUE THREAD

**Issue by dklinkman** [jazzdd86/phpVirtualbox#8]
I was playing around with building this and the result just would not run.

Turns out the cause is a bug:  https://bugs.alpinelinux.org/issues/9119  that affects php5-cli

Just FYI.  Nothing to do.  FROM alpine:3.7 or FROM alpine:edge both work fine.

But you'll want to steer clear of alpine:3.8 if you should happen to do a new build.

Nice work btw.

**Comment by jazzdd86** [comment]
Hi, thanks for looking into it. I don't have a lot of time to maintain my images lately.

If I correctly understand the bug report it should be working with Alpine 3.8.1. Did you try the latest Alpine 3.8 (3.8.1 was released 3 weeks ago)?

**Comment by jazzdd86** [comment]
Ok, tested it with apline:latest which is 3.8 right now. It works fine.
