### ISSUE TITLE
Traefik support? 

### ISSUE THREAD

**Issue by gurabli** [jazzdd86/phpVirtualbox#9]
Hi,
any idea how could I run phpvirtualbox with traefik instead of nginx? I am using traefik with Letsencrypt certs, would be great to have a working version.
Thanks

**Comment by jazzdd86** [comment]
Hi, thanks for pointing me to Traefik, never heard of it before. As of now I have not enough time to look into it. Is there no chance to point Traefik to port 80 of the phpVirtualbox container? As I understand Traefik  is a reverse proxy like nginx, so you could set it in front of the nginx proxy integrated in the phpvirtualbox container. The use of your letsencrypt certificate should work fine that way.

**Comment by Cybernemo** [comment]
Hi gurabli,
I also use Traefik and I add this to my docker-compose.yml:
```
    labels:
        - traefik.backend=phpvirtualbox
        - traefik.frontend.rule=Host:YOURDOMAIN
        - traefik.docker.network=YOURNETWORK
        - traefik.port=80
        - traefik.enable=true
```

**Comment by gurabli** [comment]
Thanks, I will try with Traefik. I use similar labels with all my other containers, but https. Will see if works with 443 port instead of 80.
